### ISSUE TITLE
Improvement: check the filename date

### ISSUE THREAD

**Issue by bclaise** [xym-tool/xym#13]
According to RFC6087bis, the convention for YANG module in IETF draft is:
<CODE BEGINS> file "blabla@2017-06-21.yang"
module blabla {

I have seen occurrences where the dates are wrongly formatted:
<CODE BEGINS> file "blabla@20170621.yang"
<CODE BEGINS> file "blabla@2017.yang"
<CODE BEGINS> file "blabla@2017/06/21.yang"
etc.

xym should check the date format.
I run a cronjob script with that functionality.
$ more checkYANGdate 
cd /home/bclaise/ietf/my-id-mirror/; for i in .; do grep BEGINS *$i* | grep yang | grep -Ev "[0-9]{4}-[0-9]{2}-[0-9]{2}" | grep -E "[0-9]{4}-"; done

**Comment by miroslavKovacPantheon** [comment]
Done with PR - https://github.com/xym-tool/xym/pull/15

**Comment by bclaise** [comment]
Solved with https://github.com/xym-tool/xym/issues/15
