### ISSUE TITLE
Extracting issue with draft-ietf-teas-yang-te-topo-02.txt 

### ISSUE THREAD

**Issue by bclaise** [xym-tool/xym#2]
xym.py draft-ietf-teas-yang-te-topo-02.txt 
ERROR: 'draft-ietf-teas-yang-te-topo-02.txt', Line 2485 - Yang file not specified in <CODE BEGINS>
ERROR: 'draft-ietf-teas-yang-te-topo-02.txt', Line 4728 - Yang file not specified in <CODE BEGINS>
Created the following models::
   ietf-te-topology.yang
   ietf-schedule.yang

If we forget about the missing file, there is still an issue with the extraction process
The extracted YANG models contain some extra lines, coming from the draft:
grep -i draft *yang
ietf-schedule@2015-12-18.yang:Internet-Draft            YANG - TE Topology               October 2015 
ietf-te-topology@2015-12-18.yang:Internet-Draft            YANG - TE Topology               October 2015 
ietf-te-topology@2015-12-18.yang:Internet-Draft            YANG - TE Topology               October 2015 
ietf-te-topology@2015-12-18.yang:Internet-Draft            YANG - TE Topology               October 2015 
ietf-te-topology@2015-12-18.yang:Internet-Draft            YANG - TE Topology               October 2015 
ietf-te-topology@2015-12-18.yang:Internet-Draft            YANG - TE Topology               October 2015 
ietf-te-topology@2015-12-18.yang:Internet-Draft            YANG - TE Topology               October 2015 
ietf-te-topology@2015-12-18.yang:Internet-Draft            YANG - TE Topology               October 2015 
ietf-te-topology@2015-12-18.yang:Internet-Draft            YANG - TE Topology               October 2015 
ietf-te-topology@2015-12-18.yang:Internet-Draft            YANG - TE Topology               October 2015 
ietf-te-topology@2015-12-18.yang:Internet-Draft            YANG - TE Topology               October 2015 
ietf-te-topology@2015-12-18.yang:Internet-Draft            YANG - TE Topology               October 2015 
ietf-te-topology@2015-12-18.yang:Internet-Draft            YANG - TE Topology               October 2015 
ietf-te-topology@2015-12-18.yang:Internet-Draft            YANG - TE Topology               October 2015 

And that obviously breaks the pyang compilation.
Note that the draft is correctly formatted according to idnits: https://www.ietf.org/tools/idnits?url=https://www.ietf.org/archive/id/draft-ietf-teas-yang-te-topo-02.txt

Regards, Benoit

**Comment by einarnn** [comment]
It seems xym is ignoring form feeds when trying to skip over page boundaries. I have a patch.

Cheers,

Einar

**Comment by einarnn** [comment]
Fixed.
