### ISSUE TITLE
xym --force-revision-pyang does not seem to work

### ISSUE THREAD

**Issue by Reshad-Rahman** [xym-tool/xym#24]
$ pyang --version
pyang 1.7.5
$ xym --force-revision-pyang https://www.ietf.org/id/draft-ietf-bfd-yang-16.txt

Extracting 'iana-bfd-types@2018-06-21.yang'

Extracting 'ietf-bfd-types@2018-06-21.yang'

Extracting 'ietf-bfd@2018-06-21.yang'

Extracting 'ietf-bfd-ip-sh@2018-06-21.yang'

Extracting 'ietf-bfd-ip-mh@2018-06-21.yang'

Extracting 'ietf-bfd-lag@2018-06-21.yang'

Extracting 'ietf-bfd-mpls@2018-06-21.yang'

Extracting 'ietf-bfd-mpls-te@2018-06-21.yang'

Extracting 'example-bfd-echo'
   ERROR: 'https://www.ietf.org/id/draft-ietf-bfd-yang-16.txt', extracting revision from file with: pyang -f name-revision ./iana-bfd-types@2018-06-21.yang has following errors:
unsupported format 'name-revision'

   ERROR: 'https://www.ietf.org/id/draft-ietf-bfd-yang-16.txt', extracting revision from file with: pyang -f name-revision ./ietf-bfd-types@2018-06-21.yang has following errors:
unsupported format 'name-revision'

   ERROR: 'https://www.ietf.org/id/draft-ietf-bfd-yang-16.txt', extracting revision from file with: pyang -f name-revision ./ietf-bfd@2018-06-21.yang has following errors:
unsupported format 'name-revision'

   ERROR: 'https://www.ietf.org/id/draft-ietf-bfd-yang-16.txt', extracting revision from file with: pyang -f name-revision ./ietf-bfd-ip-sh@2018-06-21.yang has following errors:
unsupported format 'name-revision'

   ERROR: 'https://www.ietf.org/id/draft-ietf-bfd-yang-16.txt', extracting revision from file with: pyang -f name-revision ./ietf-bfd-ip-mh@2018-06-21.yang has following errors:
unsupported format 'name-revision'

   ERROR: 'https://www.ietf.org/id/draft-ietf-bfd-yang-16.txt', extracting revision from file with: pyang -f name-revision ./ietf-bfd-lag@2018-06-21.yang has following errors:
unsupported format 'name-revision'

   ERROR: 'https://www.ietf.org/id/draft-ietf-bfd-yang-16.txt', extracting revision from file with: pyang -f name-revision ./ietf-bfd-mpls@2018-06-21.yang has following errors:
unsupported format 'name-revision'

   ERROR: 'https://www.ietf.org/id/draft-ietf-bfd-yang-16.txt', extracting revision from file with: pyang -f name-revision ./ietf-bfd-mpls-te@2018-06-21.yang has following errors:
unsupported format 'name-revision'

   ERROR: 'https://www.ietf.org/id/draft-ietf-bfd-yang-16.txt', extracting revision from file with: pyang -f name-revision ./example-bfd-echo.yang has following errors:
unsupported format 'name-revision'

Created the following models:
iana-bfd-types@2018-06-21.yang
ietf-bfd-types@2018-06-21.yang
ietf-bfd@2018-06-21.yang
ietf-bfd-ip-sh@2018-06-21.yang
ietf-bfd-ip-mh@2018-06-21.yang
ietf-bfd-lag@2018-06-21.yang
ietf-bfd-mpls@2018-06-21.yang
ietf-bfd-mpls-te@2018-06-21.yang
example-bfd-echo.yang
$ xym --version
xym 0.4.2

**Comment by einarnn** [comment]
Can you describe the issue in a little more detail?
