### ISSUE TITLE
Support for module example in leaf description

### ISSUE THREAD

**Issue by bclaise** [xym-tool/xym#5]
I found a bug with the latest restconf draft https://tools.ietf.org/html/draft-ietf-netconf-restconf-14

There is an issue with the YANG module extraction
    xym.py draft-ietf-netconf-restconf-14.txt
    ERROR: 'draft-ietf-netconf-restconf-14.txt', Line 3930 - 'module' statement within another module
    Created the following models::
       example-ops.yang
       example-actions.yang
       example-jukebox.yang
       example-mod.yang

Not an issue with the draft, but with the xym.py that can't deal with a module definition in a description:

    container operations {
               description
                 "Container for all operation resources
                  (application/yang-operation),

                  Each resource is represented as an empty leaf with the
                  name of the RPC operation from the YANG rpc statement.
                  For example, the 'system-restart' RPC operation defined
                  in the 'ietf-system' module would be represented as
                  an empty leaf in the 'ietf-system' namespace. This is
                  a conceptual leaf, and will not actually be found in
                  the module:

                     module ietf-system {                        <=====
                       leaf system-reset {
                         type empty;
                       }
                     }

**Comment by VinodKumarS-Huawei** [comment]
Fix is merged in the below commit

https://github.com/xym-tool/xym/commit/5c2d5a61e9e14074cd8e0c99109ad896e84755aa

**Comment by bclaise** [comment]
Fix works fine. Thanks.
